server:
  port: 8787

spring:
  application:
    name: config-server
  #profiles:
  #  active: dev  # native 配置使用本地储存 dev github的配置
  cloud:
    config:
      server:
       # native:
       #   search-locations: classpath:properties/ # 搜索src/main/resource 下的properties文件夹下的文
        git:
          uri: https://github.com/JamesZow/Spring-Cloud-Project     # 配置git仓库的地址
          search-paths: springCloudConfigDirectory                 # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号（私有库必填）
          password:                                             # git仓库的密码（私有库必填）
          default-label: master                                  #配置仓库的分支

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8888/eureka/